name: Build My App Image

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker:
    uses: Onemind-Services-LLC/actions/.github/workflows/docker-build-push.yml@main
    with:
      image: ghcr.io/onemind/my-app
      cache-image: ghcr.io/onemind/my-app:buildcache-main
      registry: ghcr.io
    secrets:
      username: ${{ secrets.GHCR_USERNAME }}
      password: ${{ secrets.GHCR_TOKEN }}
